#!/bin/bash
# Install script

function Usage() {
    cat - <<ENDTEXT

$0 -dev|-live|-to directory

    Install in the dev or live environment or into the specified directory.

    -dev  --dev         - install in the dev environment
    -live --live        - install in the live environment
    -to --to directory  - install in the specified directory

ENDTEXT
    exit 5
}
function checkVarIsSet() {
    if [ "${!1}" == "" ]; then
        echo "$1" env var is not set
        exit 5
    fi
}
# cmd line args:
baseDir=""              # to install into. Default is nowhere
while [ $# -gt 0 ]; do
    case "$1" in
    -h|--help) Usage ;;
    -dev|--dev)   checkVarIsSet DEV ; baseDir="$DEV";  shift; ;;
    -live|--live) checkVarIsSet LIVE; baseDir="$LIVE"; shift; ;;
    -to|--to)     baseDir="$2"; shift; shift; ;;
    -*|--*) echo "invalid option $1"; Usage ;;
    *) break; ;;
    esac
done

if [ "$baseDir" == "" ]; then Usage; fi

# Places where things get installed
binDir=$baseDir/bin
libPythonDir=$baseDir/lib/python

# Check install directories exist
if [ ! -d $binDir ]; then
    echo "$binDir" is not a directory
    exit 5
fi
if [ ! -d $libPythonDir ]; then
    echo "$libPythonDir" is not a directory
    exit 5
fi

echo "Installing into $binDir"
\cp -p bin/[a-z]* $binDir       # everything but the Old directory
saveCode="$?"
if [ $saveCode != 0 ]; then
    echo "Something went wrong. Exit code $saveCode"
    exit $saveCode
fi

echo "Installing into $libPythonDir"
\cp -p lib/python/*.py $libPythonDir
saveCode="$?"
if [ $saveCode != 0 ]; then
    echo "Something went wrong. Exit code $saveCode"
    exit $saveCode
fi
echo "Files in dotFiles/ are not installed automatically. Do these by hand"
